### ISSUE TITLE
walkseq data missing

### ISSUE THREAD

**Issue by alphonse-lin** [Kazerujoy/road2vec#1]
Thank you so much for your contribution! I have read your code, but I cannot find a file called _walkseq_all20219239.txt_. Would it be possible for you to upload this file as well? 

Or, if this data is highly related to privacy, then would it be possible for you to upload the _ouput.txt_, so I could have a chance to see the outcome of this model?

Thx

**Comment by Kazerujoy** [comment]
It's a private dataset, but i can tell about how to get a dataset likely.  
First you can get a public map file from osm https://www.openstreetmap.org/ it contains nodes info and way info. resolve them to graph node/edge-like data and encode data in someway such as grids encoding or geohash encoding. Then goes the deepwalk.  
A row of walkseq is like 
280854763_0, 87525061_18, 87525061_18, 280854767_0, 280854767_1, 280854770_1, 347622342_1, 347622342_0
the a of " a-b " is the osm road_id of a road and the second is the path index of a road. (a road contain serval paths)  
a output file will be uploaded. sorry about the late response.
